# Generated by Django 5.2.17 on 2026-10-01 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_disable_legacy_seed_delivery"),
        ("payments", "0002_alfa_bank"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Проба ожидает завершения"),
                            ("succeeded", "Проба завершена успешно"),
                            ("canceled", "Проба отменена"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Результат пробы",
                    ),
                ),
                ("action_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("snapshot", models.JSONField(editable=False, verbose_name="Сохранённый заказ для пробы")),
                (
                    "order",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trial_payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пробная оплата без списания",
                "verbose_name_plural": "Пробные оплаты без списания",
                "ordering": ["-created_at"],
            },
        ),
    ]
