# Generated by Django 5.2.17 on 2026-09-13 13:54

from django.db import migrations, models

from apps.orders.migration_compat import AddFieldIfMissing, RemoveConstraintIfExists


def identify_manager_notifications(apps, schema_editor):
    notification = apps.get_model("orders", "Notification")
    notification.objects.using(schema_editor.connection.alias).exclude(
        recipient=models.F("order__email")
    ).update(audience="manager")


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        RemoveConstraintIfExists(
            model_name="notification",
            name="one_order_notification",
        ),
        AddFieldIfMissing(
            model_name="notification",
            name="audience",
            field=models.CharField(
                choices=[("customer", "Покупатель"), ("manager", "Менеджер")],
                default="customer",
                max_length=12,
                verbose_name="Кому",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="test_mode",
            field=models.BooleanField(default=False, editable=False, verbose_name="Тестовый заказ"),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="manager_email",
            field=models.EmailField(
                blank=True,
                help_text="На этот адрес приходят новые заказы и подтверждения оплаты. Изменение действует для новых уведомлений.",
                max_length=254,
                verbose_name="Почта менеджера по продажам",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("order", "event", "recipient", "audience"), name="one_order_audience_notification"
            ),
        ),
        migrations.RunPython(identify_manager_notifications, migrations.RunPython.noop),
    ]
