# Generated by Django 5.2.17 on 2026-10-02 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_product_package_measured_at_and_more"),
        ("orders", "0006_merge_checkout_and_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("name", models.CharField(max_length=160, verbose_name="Название коробки")),
                ("code", models.SlugField(unique=True, verbose_name="Код коробки")),
                (
                    "inner_length_mm",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Внутренняя длина, мм",
                    ),
                ),
                (
                    "inner_width_mm",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Внутренняя ширина, мм",
                    ),
                ),
                (
                    "inner_height_mm",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Внутренняя высота, мм",
                    ),
                ),
                (
                    "outer_length_mm",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Внешняя длина, мм",
                    ),
                ),
                (
                    "outer_width_mm",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Внешняя ширина, мм",
                    ),
                ),
                (
                    "outer_height_mm",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Внешняя высота, мм",
                    ),
                ),
                (
                    "tare_weight_g",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Вес пустой коробки, г",
                    ),
                ),
                (
                    "max_weight_g",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Предельный вес коробки с содержимым, г",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Коробка доступна для сборки")),
            ],
            options={
                "verbose_name": "Коробка",
                "verbose_name_plural": "Коробки",
                "ordering": ["name", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("inner_length_mm__gt", 0)),
                        name="packingbox_positive_inner_length_mm",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("inner_width_mm__gt", 0)),
                        name="packingbox_positive_inner_width_mm",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("inner_height_mm__gt", 0)),
                        name="packingbox_positive_inner_height_mm",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("outer_length_mm__gt", 0)),
                        name="packingbox_positive_outer_length_mm",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("outer_width_mm__gt", 0)),
                        name="packingbox_positive_outer_width_mm",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("outer_height_mm__gt", 0)),
                        name="packingbox_positive_outer_height_mm",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("tare_weight_g__gt", 0)), name="packingbox_positive_tare_weight_g"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_weight_g__gt", 0)), name="packingbox_positive_max_weight_g"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("tare_weight_g__lt", models.F("max_weight_g"))),
                        name="packingbox_tare_below_limit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("inner_length_mm__lte", models.F("outer_length_mm"))),
                        name="packingbox_inner_length_fits_outer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("inner_width_mm__lte", models.F("outer_width_mm"))),
                        name="packingbox_inner_width_fits_outer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("inner_height_mm__lte", models.F("outer_height_mm"))),
                        name="packingbox_inner_height_fits_outer",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PackingRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("name", models.CharField(max_length=160, verbose_name="Название схемы")),
                (
                    "packing_weight_g",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Вес наполнителя, вставок и скотча, г"
                    ),
                ),
                (
                    "measured_weight_g",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Измеренный вес готовой посылки, г",
                    ),
                ),
                (
                    "outer_length_mm",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Измеренная длина посылки, мм",
                    ),
                ),
                (
                    "outer_width_mm",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Измеренная ширина посылки, мм",
                    ),
                ),
                (
                    "outer_height_mm",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Измеренная высота посылки, мм",
                    ),
                ),
                ("instructions", models.TextField(blank=True, verbose_name="Как собрать посылку")),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="Использовать для расчёта доставки"),
                ),
                ("measurement_signature", models.CharField(blank=True, editable=False, max_length=64)),
                (
                    "measured_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Сборка и замеры подтверждены"
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipes",
                        to="orders.packingbox",
                        verbose_name="Коробка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Схема упаковки",
                "verbose_name_plural": "Схемы упаковки",
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PackingRecipeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Количество в коробке",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.product",
                        verbose_name="Товар / вариант",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.packingrecipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в схеме",
                "verbose_name_plural": "Состав коробки",
                "ordering": ["product_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="packingrecipe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("measured_weight_g__isnull", True), ("measured_weight_g__gt", 0), _connector="OR"
                ),
                name="packingrecipe_positive_measured_weight_g",
            ),
        ),
        migrations.AddConstraint(
            model_name="packingrecipe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outer_length_mm__isnull", True), ("outer_length_mm__gt", 0), _connector="OR"
                ),
                name="packingrecipe_positive_outer_length_mm",
            ),
        ),
        migrations.AddConstraint(
            model_name="packingrecipe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outer_width_mm__isnull", True), ("outer_width_mm__gt", 0), _connector="OR"
                ),
                name="packingrecipe_positive_outer_width_mm",
            ),
        ),
        migrations.AddConstraint(
            model_name="packingrecipe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outer_height_mm__isnull", True), ("outer_height_mm__gt", 0), _connector="OR"
                ),
                name="packingrecipe_positive_outer_height_mm",
            ),
        ),
        migrations.AddConstraint(
            model_name="packingrecipeitem",
            constraint=models.UniqueConstraint(
                fields=("recipe", "product"), name="packingrecipe_unique_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="packingrecipeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1), ("quantity__lte", 100)),
                name="packingrecipeitem_quantity_range",
            ),
        ),
    ]
