# Generated by Django 5.2.17 on 2026-10-04 12:38

from django.db import migrations, models


def preserve_manager(apps, schema_editor):
    alias = schema_editor.connection.alias
    Store = apps.get_model("orders", "StoreSettings")
    Notifications = apps.get_model("orders", "NotificationSettings")
    store = Store.objects.using(alias).filter(pk=1).first()
    if store and store.manager_email.strip():
        config, _ = Notifications.objects.using(alias).get_or_create(pk=1)
        if not config.manager_email.strip():
            config.manager_email = store.manager_email.strip()
            config.save(using=alias, update_fields=["manager_email"])


def restore_manager(apps, schema_editor):
    alias = schema_editor.connection.alias
    config = apps.get_model("orders", "NotificationSettings").objects.using(alias).filter(pk=1).first()
    if config:
        apps.get_model("orders", "StoreSettings").objects.using(alias).filter(pk=1).update(
            manager_email=config.manager_email
        )


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_packingrecipe_test_only"),
    ]

    operations = [
        migrations.RunPython(preserve_manager, restore_manager),
        migrations.RemoveField(
            model_name="storesettings",
            name="manager_email",
        ),
        migrations.AddField(
            model_name="order",
            name="access_version",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, editable=False, max_length=80, verbose_name="Трек-номер"),
        ),
    ]
