# Generated by Django 5.2.17 on 2026-10-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_remove_storesettings_manager_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packingbox",
            name="auto_enabled",
            field=models.BooleanField(default=False, verbose_name="Использовать для автоматического подбора"),
        ),
        migrations.AddField(
            model_name="packingbox",
            name="auto_filler_weight_g",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Вес общих материалов, скотча и наполнителя, г"
            ),
        ),
        migrations.AddField(
            model_name="packingbox",
            name="auto_measured_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Параметры автоподбора подтверждены"
            ),
        ),
        migrations.AddField(
            model_name="packingbox",
            name="auto_measurement_signature",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="packingbox",
            name="auto_padding_mm",
            field=models.PositiveIntegerField(default=0, verbose_name="Защитный отступ от каждой стенки, мм"),
        ),
        migrations.AddField(
            model_name="packingbox",
            name="auto_test_only",
            field=models.BooleanField(default=False, verbose_name="Учебная коробка автоподбора"),
        ),
        migrations.AddField(
            model_name="packingbox",
            name="source_url",
            field=models.URLField(blank=True, verbose_name="Источник типоразмера"),
        ),
        migrations.AddField(
            model_name="packingbox",
            name="supplier",
            field=models.CharField(
                choices=[
                    ("cdek", "Покупаем у СДЭК"),
                    ("own", "Другой поставщик"),
                    ("demo", "Учебный пример"),
                ],
                default="own",
                max_length=12,
                verbose_name="Источник коробки",
            ),
        ),
    ]
