# Generated by Django 5.2.17 on 2026-10-05 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_packingbox_auto_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packingbox",
            name="reference_note",
            field=models.TextField(
                blank=True,
                help_text="Ориентир из каталога. Не заменяет замер внутреннего пространства, внешних размеров и тары.",
                verbose_name="Справочные сведения поставщика",
            ),
        ),
        migrations.AlterField(
            model_name="packingbox",
            name="inner_height_mm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Внутренняя высота, мм",
            ),
        ),
        migrations.AlterField(
            model_name="packingbox",
            name="inner_length_mm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Внутренняя длина, мм",
            ),
        ),
        migrations.AlterField(
            model_name="packingbox",
            name="inner_width_mm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Внутренняя ширина, мм",
            ),
        ),
        migrations.AlterField(
            model_name="packingbox",
            name="max_weight_g",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Предельный вес коробки с содержимым, г",
            ),
        ),
        migrations.AlterField(
            model_name="packingbox",
            name="outer_height_mm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Внешняя высота, мм",
            ),
        ),
        migrations.AlterField(
            model_name="packingbox",
            name="outer_length_mm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Внешняя длина, мм",
            ),
        ),
        migrations.AlterField(
            model_name="packingbox",
            name="outer_width_mm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Внешняя ширина, мм",
            ),
        ),
        migrations.AlterField(
            model_name="packingbox",
            name="tare_weight_g",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Вес пустой коробки, г",
            ),
        ),
    ]
