# Generated by Django 5.2.17 on 2026-10-05 10:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_packingbox_reference_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packingbox",
            name="auto_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Коробка и общие материалы на одно место, ₽",
            ),
        ),
        migrations.AddField(
            model_name="packingbox",
            name="auto_price_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Выберите способ учёта"),
                    ("included", "Учтена в цене товара"),
                    ("charge", "Добавлять к доставке"),
                ],
                default="",
                max_length=12,
                verbose_name="Как учитывать стоимость упаковки",
            ),
        ),
    ]
