import { test, expect } from '@playwright/test'

const add = (page) => page.getByRole('button', { name: 'Добавить в корзину', exact: true })
const count = (page) => page.locator('#cart-toggle [data-cart-count]')
const plus = (root) => root.getByRole('button', { name: 'Увеличить количество', exact: true })
const minus = (root) => root.getByRole('button', { name: 'Уменьшить количество', exact: true })

for (const width of [1440, 390]) {
  test(`silent catalog counters, product and cart stay synchronized at ${width}px`, async ({
    page,
    context,
  }) => {
    await page.setViewportSize({ width, height: 900 })
    const errors = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/')
    if (await page.getByRole('button', { name: 'Понятно', exact: true }).isVisible())
      await page.getByRole('button', { name: 'Понятно', exact: true }).click()
    const tile = page.locator('.product-tile').filter({ hasText: 'Тестовый товар 1' }).first()
    const url = await tile.getByRole('link', { name: 'Подробнее' }).getAttribute('href')
    await add(tile).click()
    await expect(count(page)).toHaveText('1')
    await expect(page.locator('#cart-dialog')).not.toBeVisible()
    await plus(tile).click()
    await expect(count(page)).toHaveText('2')
    await expect(tile.locator('[name=quantity]')).toHaveValue('2')
    await expect(plus(tile)).toBeFocused()
    await tile.evaluate((node) => window.scrollTo(0, node.getBoundingClientRect().top + scrollY - 100))
    await page.screenshot({ path: `var/artifacts/purchase/catalog-${width}.png` })
    await page.evaluate(() => scrollTo(0, 900))
    expect(Math.abs((await page.locator('.shop-header').boundingBox()).y)).toBeLessThan(1)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.goto(url)
    const product = page.locator('.product-buy')
    await expect(product.locator('[name=quantity]')).toHaveValue('2')
    await minus(product).click()
    await expect(count(page)).toHaveText('1')
    await page.locator('#cart-toggle').click()
    const drawer = page.locator('#cart-dialog')
    await plus(drawer).click()
    await expect(drawer.locator('[name=quantity]')).toHaveValue('2')
    await expect(count(page)).toHaveText('2')
    await expect(drawer.locator('.cart-content')).toHaveAttribute('aria-busy', 'false')
    await page.screenshot({ path: `var/artifacts/purchase/cart-${width}.png` })
    await page.keyboard.press('Escape')
    await expect(product.locator('[name=quantity]')).toHaveValue('2')
    const second = await context.newPage()
    await second.goto(url)
    await minus(second.locator('.product-buy')).click()
    await expect(count(second)).toHaveText('1')
    await expect(product.locator('[name=quantity]')).toHaveValue('1')
    await second.close()
    await minus(product).click()
    await expect(count(page)).toHaveText('0')
    await expect(add(page)).toBeVisible()
    await expect(page.locator('#cart-dialog')).not.toBeVisible()
    expect(errors).toEqual([])
  })

  test(`recipient fields, formatted paste and responsive wheel zoom at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.route('https://tile.openstreetmap.org/**', (route) =>
      route.fulfill({
        contentType: 'image/svg+xml',
        body: '<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" fill="#edf1ed"/><path d="M0 100h256M80 0v256" stroke="#fff" stroke-width="10"/></svg>',
      }),
    )
    await page.goto('/products/test-product-1/')
    await add(page).click()
    await expect(count(page)).toHaveText('1')
    await page.goto('/checkout/')
    if (await page.getByRole('button', { name: 'Понятно', exact: true }).isVisible())
      await page.getByRole('button', { name: 'Понятно', exact: true }).click()
    await expect(page.getByLabel('Имя', { exact: true })).toHaveAttribute('required', '')
    await expect(page.getByLabel('Фамилия', { exact: true })).toHaveAttribute('required', '')
    await expect(page.getByLabel('Отчество', { exact: false })).not.toHaveAttribute('required')
    await page.getByLabel('Имя', { exact: true }).fill('Анна')
    await page.getByLabel('Фамилия', { exact: true }).fill('Иванова')
    const phone = page.getByLabel('Телефон', { exact: true })
    await phone.fill('9991234567')
    await expect(phone).toHaveValue('(999) 123-45-67')
    await phone.press('End')
    await phone.press('9')
    await expect(phone).toHaveValue('(999) 123-45-67')
    await phone.evaluate((node) => {
      node.focus()
      node.select()
      const data = new DataTransfer()
      data.setData('text/plain', '+375 (29) 123-45-67')
      node.dispatchEvent(
        new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }),
      )
    })
    await expect(page.getByLabel('Код страны', { exact: true })).toHaveValue('BY')
    await expect(phone).toHaveValue('(29) 123-45-67')
    await phone.fill('+7 (999) 123-45-67')
    await expect(page.getByLabel('Код страны', { exact: true })).toHaveValue('RU')
    await expect(phone).toHaveValue('(999) 123-45-67')
    await page.screenshot({ path: `var/artifacts/purchase/checkout-${width}.png` })
    await page.getByLabel('Способ получения').selectOption({ label: 'Тестовый СДЭК до ПВЗ' })
    await expect(page.getByLabel('Фамилия', { exact: true })).toHaveValue('Иванова')
    await expect(phone).toHaveValue('(999) 123-45-67')
    const map = page.locator('#cdek-map')
    await expect(map.locator('.cdek-marker').first()).toBeVisible()
    await map.scrollIntoViewIfNeeded()
    const box = await map.boundingBox()
    expect(box.width).toBeGreaterThan(width === 1440 ? 900 : width - 40)
    expect(box.height).toBeLessThan(650)
    const transform = await map.locator('.leaflet-tile-container').first().getAttribute('style')
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
    await page.mouse.wheel(0, -120)
    await expect
      .poll(() => map.locator('.leaflet-tile-container').first().getAttribute('style'))
      .not.toBe(transform)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `var/artifacts/purchase/map-${width}.png` })
  })
}
