# Generated by Django 5.2.17 on 2026-09-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время")),
                ("kind", models.CharField(max_length=80, verbose_name="Событие")),
                ("object_id", models.CharField(max_length=80, verbose_name="Объект")),
                ("message", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Системное событие",
                "verbose_name_plural": "Системные события",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("window_start", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
