# Generated by Django 5.2.17 on 2026-10-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("catalog", "Реальный ассортимент и сведения продавца"),
                            ("shipping", "Расчёт СДЭК сверён с накладной"),
                            ("email", "Письма получены покупателем и компанией"),
                            ("checkout", "Оформление проверено на опубликованном магазине"),
                            ("payment", "Банковская оплата и возврат проверены"),
                            ("fiscal", "Чеки оплаты, передачи и возврата проверены"),
                            ("operations", "Таймеры, оповещения и восстановление проверены"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Проверка",
                    ),
                ),
                (
                    "reference",
                    models.TextField(
                        help_text="Дата, среда, ответственный и ссылка/номер протокола с результатом. Без ключей и данных покупателей.",
                        verbose_name="Протокол проверки",
                    ),
                ),
                ("confirmed_at", models.DateTimeField(auto_now=True, verbose_name="Подтверждено")),
                ("configuration_digest", models.CharField(editable=False, max_length=64)),
            ],
            options={
                "verbose_name": "Приёмка магазина",
                "verbose_name_plural": "Приёмка магазина",
            },
        ),
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("finished_at", models.DateTimeField()),
                ("failures", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
