# Generated by Django 5.2.17 on 2026-09-11 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "idempotence_key",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="Ключ операции"
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="ID ЮKassa",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Сумма")),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="Валюта")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("creating", "Создаётся"),
                            ("unknown", "Требуется сверка"),
                            ("pending", "Ожидает оплаты"),
                            ("waiting_for_capture", "Ожидает подтверждения"),
                            ("succeeded", "Успешен"),
                            ("canceled", "Отменён"),
                        ],
                        db_index=True,
                        default="creating",
                        max_length=24,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "confirmation_url",
                    models.URLField(blank=True, max_length=1000, verbose_name="Адрес оплаты"),
                ),
                ("request_payload", models.JSONField(default=dict, editable=False)),
                (
                    "last_checked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Последняя сверка"),
                ),
                ("last_error", models.CharField(blank=True, max_length=200, verbose_name="Ошибка")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deduplication_key", models.CharField(max_length=160, unique=True)),
                ("event_type", models.CharField(max_length=60, verbose_name="Событие")),
                ("verified_at", models.DateTimeField(auto_now_add=True, verbose_name="Проверено")),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="payments.paymentattempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие платежа",
                "verbose_name_plural": "События платежей",
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("provider_id", models.CharField(max_length=64, unique=True, verbose_name="ID возврата")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Сумма")),
                ("currency", models.CharField(max_length=3, verbose_name="Валюта")),
                ("state", models.CharField(max_length=20, verbose_name="Состояние")),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.paymentattempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Возврат",
                "verbose_name_plural": "Возвраты",
            },
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["creating", "unknown", "pending", "waiting_for_capture"])),
                fields=("order",),
                name="one_active_payment_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="refund_amount_positive"
            ),
        ),
    ]
