# Generated by Django 5.2.17 on 2026-09-11 17:09

import content.uploads
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликован"), ("archived", "Архив")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="Публикация",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата публикации")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("show_on_home", models.BooleanField(default=False, verbose_name="Показывать на главной")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Последнее изменение")),
                ("author", models.CharField(max_length=150, verbose_name="Имя автора")),
                ("organization", models.CharField(blank=True, max_length=200, verbose_name="Организация")),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                ("date", models.DateField(verbose_name="Дата отзыва")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        storage=content.uploads.PrivateMediaStorage(),
                        upload_to=content.uploads.private_upload_path,
                        validators=[content.uploads.validate_image],
                        verbose_name="Фотография или логотип",
                    ),
                ),
                (
                    "publication_basis",
                    models.TextField(
                        blank=True,
                        help_text="Внутренняя запись: источник и разрешение автора. На сайте не отображается.",
                        verbose_name="Основание для публикации",
                    ),
                ),
                (
                    "industries",
                    models.ManyToManyField(blank=True, to="content.industry", verbose_name="Направления"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="reviews", to="catalog.product", verbose_name="Товары"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ("order", "pk"),
                "permissions": [("publish_review", "Может публиковать отзывы")],
                "abstract": False,
            },
        ),
    ]
