# Generated by Django 5.2.17 on 2026-09-11 17:09

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("name", models.CharField(max_length=160, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Адрес")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("active", models.BooleanField(default=True, verbose_name="Активна")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("name", models.CharField(max_length=240, verbose_name="Название")),
                ("slug", models.SlugField(max_length=240, unique=True, verbose_name="Адрес")),
                ("sku", models.CharField(max_length=80, unique=True, verbose_name="Артикул")),
                ("short_description", models.TextField(blank=True, verbose_name="Краткое описание")),
                ("description", models.TextField(blank=True, verbose_name="Полное описание")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Цена, ₽",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликован"), ("archived", "Архив")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="Публикация",
                    ),
                ),
                ("purchasable", models.BooleanField(default=False, verbose_name="Доступен для покупки")),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Количество на складе")),
                (
                    "reserved_stock",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="В резерве"),
                ),
                (
                    "vat_code",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Ставка НДС ЮKassa"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="catalog.category", verbose_name="Категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Характеристика")),
                ("value", models.CharField(max_length=500, verbose_name="Значение")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=catalog.models.product_image_path,
                        validators=[catalog.models.validate_image],
                        verbose_name="Изображение",
                    ),
                ),
                ("alt", models.CharField(max_length=240, verbose_name="Описание изображения")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0), ("price__isnull", True), _connector="OR"),
                name="product_positive_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_stock__lte", models.F("stock"))),
                name="stock_covers_reservations",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("purchasable", False), ("price__isnull", False), _connector="OR"),
                name="purchasable_has_price",
            ),
        ),
    ]
