# Generated by Django 5.2.17 on 2026-10-01 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="package_height_cm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Высота упаковки, см",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_length_cm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Длина упаковки, см",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_weight_g",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Вес одного упакованного товара, г",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_width_cm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Ширина упаковки, см",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="vat_code",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Код ставки НДС"),
        ),
    ]
