# Generated by Django 5.2.17 on 2026-09-11 17:11

import apps.catalog.models
import apps.catalog.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                storage=apps.catalog.storage.ProductImageStorage(),
                upload_to=apps.catalog.models.product_image_path,
                validators=[apps.catalog.models.validate_image],
                verbose_name="Изображение",
            ),
        ),
    ]
