# Generated by Django 5.2.17 on 2026-10-02 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_package_height_cm_product_package_length_cm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="package_measured_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Замеры отдельной посылки подтверждены"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="package_measurement_signature",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_mode",
            field=models.CharField(
                choices=[
                    ("individual", "Отдельная посылка для каждой единицы"),
                    ("combined", "Общая коробка по проверенной схеме"),
                ],
                default="individual",
                max_length=12,
                verbose_name="Как упаковывать",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_height_mm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Высота товара с защитой, мм",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_length_mm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Длина товара с защитой, мм",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_weight_g",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Вес товара с индивидуальной защитой, г",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_width_mm",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Ширина товара с защитой, мм",
            ),
        ),
    ]
