# Generated by Django 5.2.17 on 2026-10-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_product_package_measured_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit_allow_rotation",
            field=models.BooleanField(default=False, verbose_name="Разрешено переворачивать товар с защитой"),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_measured_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Параметры автоподбора подтверждены"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_measurement_signature",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_packing_group",
            field=models.SlugField(
                default="general",
                help_text="Только товары одной группы объединяются автоматически. Например: cosmetics, equipment.",
                max_length=64,
                verbose_name="Группа совместной упаковки",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_stack_limit_g",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 — сверху ничего не ставить. Укажите проверенную нагрузку для защищённого товара.",
                verbose_name="Допустимый вес сверху, г",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_test_only",
            field=models.BooleanField(default=False, verbose_name="Учебные параметры автоподбора"),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_mode",
            field=models.CharField(
                choices=[
                    ("individual", "Отдельная посылка для каждой единицы"),
                    ("combined", "Общая коробка по проверенной схеме"),
                    ("automatic", "Автоматический подбор общей коробки"),
                ],
                default="individual",
                max_length=12,
                verbose_name="Как упаковывать",
            ),
        ),
    ]
