# Generated by Django 5.2.17 on 2026-09-11 17:09

import content.uploads
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=100, unique=True, verbose_name="Ключ поля")),
                ("label", models.CharField(max_length=200, verbose_name="Название поля")),
                ("value", models.TextField(blank=True, verbose_name="Текст")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Последнее изменение")),
            ],
            options={
                "verbose_name": "Текст сайта",
                "verbose_name_plural": "Тексты сайта",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликован"), ("archived", "Архив")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="Публикация",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата публикации")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("show_on_home", models.BooleanField(default=False, verbose_name="Показывать на главной")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Последнее изменение")),
                (
                    "source_key",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="Ключ первоначального импорта",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Адрес подборки")),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                ("intro", models.TextField(verbose_name="Введение")),
                (
                    "image_base",
                    models.SlugField(blank=True, max_length=100, verbose_name="Ключ исходного изображения"),
                ),
                (
                    "handbook_chapter",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Страница справочника"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тематическая подборка",
                "verbose_name_plural": "Тематические подборки",
                "ordering": ("order", "pk"),
                "permissions": [("publish_collection", "Может публиковать подборки")],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectionAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Прежний адрес подборки")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="content.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прежний адрес подборки",
                "verbose_name_plural": "Прежние адреса подборок",
            },
        ),
        migrations.CreateModel(
            name="CollectionSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("body", models.TextField(verbose_name="Текст")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="content.collection",
                        verbose_name="Подборка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел подборки",
                "verbose_name_plural": "Разделы подборки",
                "ordering": ("order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликован"), ("archived", "Архив")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="Публикация",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата публикации")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("show_on_home", models.BooleanField(default=False, verbose_name="Показывать на главной")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Последнее изменение")),
                (
                    "source_key",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="Ключ первоначального импорта",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Постоянный адрес")),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Краткое описание")),
                ("material_type", models.CharField(max_length=100, verbose_name="Тип материала")),
                (
                    "file",
                    models.FileField(
                        storage=content.uploads.PrivateMediaStorage(),
                        upload_to=content.uploads.private_upload_path,
                        validators=[content.uploads.validate_pdf],
                        verbose_name="PDF",
                    ),
                ),
                ("pages", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Страниц")),
                (
                    "is_declaration",
                    models.BooleanField(default=False, verbose_name="Декларация соответствия"),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=100, verbose_name="Категория декларации"),
                ),
                (
                    "registration",
                    models.CharField(blank=True, max_length=200, verbose_name="Регистрационный номер"),
                ),
                (
                    "valid_until_label",
                    models.CharField(blank=True, max_length=150, verbose_name="Срок действия"),
                ),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="content.collection",
                        verbose_name="Тематические подборки",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="catalog.product", verbose_name="Товары"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ("order", "pk"),
                "permissions": [("publish_document", "Может публиковать документы")],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=250, unique=True, verbose_name="Прежний путь или slug")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="content.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прежний адрес документа",
                "verbose_name_plural": "Прежние адреса документов",
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликован"), ("archived", "Архив")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="Публикация",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата публикации")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("show_on_home", models.BooleanField(default=False, verbose_name="Показывать на главной")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Последнее изменение")),
                (
                    "source_key",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        null=True,
                        unique=True,
                        verbose_name="Ключ первоначального импорта",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Ключ отраслевой сцены")),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("caption", models.TextField(verbose_name="Описание")),
                ("action_label", models.CharField(max_length=150, verbose_name="Текст ссылки")),
                ("image_base", models.SlugField(max_length=100, verbose_name="Ключ исходного изображения")),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.collection",
                        verbose_name="Материалы по направлению",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отраслевой сценарий",
                "verbose_name_plural": "Отраслевые сценарии",
                "ordering": ("order", "pk"),
                "permissions": [("publish_industry", "Может публиковать отраслевые сценарии")],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="document",
            name="industries",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="content.industry", verbose_name="Направления"
            ),
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("singleton", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Название компании"),
                ),
                (
                    "legal_name",
                    models.CharField(blank=True, max_length=250, verbose_name="Юридическое наименование"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Электронная почта")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[0-9]{7,15}$", "Укажите международный номер без пробелов."
                            )
                        ],
                        verbose_name="Телефон для ссылки",
                    ),
                ),
                (
                    "phone_label",
                    models.CharField(blank=True, max_length=40, verbose_name="Телефон для отображения"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "footer_label",
                    models.CharField(blank=True, max_length=300, verbose_name="Подпись в подвале"),
                ),
            ],
            options={
                "verbose_name": "Контакты и сведения о компании",
                "verbose_name_plural": "Контакты и сведения о компании",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("singleton", 1)), name="site_settings_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликован"), ("archived", "Архив")],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="Публикация",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата публикации")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("show_on_home", models.BooleanField(default=False, verbose_name="Показывать на главной")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Последнее изменение")),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "provider",
                    models.CharField(
                        choices=[("rutube", "Rutube"), ("youtube", "YouTube"), ("vimeo", "Vimeo")],
                        max_length=20,
                        verbose_name="Видеосервис",
                    ),
                ),
                (
                    "provider_id",
                    models.CharField(
                        max_length=80,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9_-]+$", "Только идентификатор видео, без HTML и URL."
                            )
                        ],
                        verbose_name="Идентификатор видео",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        storage=content.uploads.PrivateMediaStorage(),
                        upload_to=content.uploads.private_upload_path,
                        validators=[content.uploads.validate_image],
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "industries",
                    models.ManyToManyField(blank=True, to="content.industry", verbose_name="Направления"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="videos", to="catalog.product", verbose_name="Товары"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
                "ordering": ("order", "pk"),
                "permissions": [("publish_video", "Может публиковать видео")],
                "abstract": False,
            },
        ),
    ]
