# Generated by Django 5.2.17 on 2026-09-30 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="Вопрос")),
                (
                    "answer",
                    models.TextField(
                        help_text="Обычный текст. Переменные: {delivery_price}, {email}, {phone}.",
                        verbose_name="Ответ",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Показывать на сайте")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Вопрос и ответ",
                "verbose_name_plural": "Вопросы и ответы",
                "ordering": ("order", "pk"),
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bank_account",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[django.core.validators.RegexValidator("^\\d{20}$", "Счёт: 20 цифр.")],
                verbose_name="Расчётный счёт",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bank_bik",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[django.core.validators.RegexValidator("^\\d{9}$", "БИК: 9 цифр.")],
                verbose_name="БИК",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bank_name",
            field=models.CharField(blank=True, max_length=250, verbose_name="Банк"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="correspondent_account",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[django.core.validators.RegexValidator("^\\d{20}$", "Счёт: 20 цифр.")],
                verbose_name="Корреспондентский счёт",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="inn",
            field=models.CharField(
                blank=True,
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator("^(\\d{10}|\\d{12})$", "ИНН: 10 или 12 цифр.")
                ],
                verbose_name="ИНН",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="kpp",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[django.core.validators.RegexValidator("^\\d{9}$", "КПП: 9 цифр.")],
                verbose_name="КПП (для организации)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="postal_address",
            field=models.TextField(blank=True, verbose_name="Почтовый адрес для обращений"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_authority",
            field=models.CharField(blank=True, max_length=300, verbose_name="Регистрирующий орган"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(\\d{13}|\\d{15})$", "ОГРН: 13 цифр; ОГРНИП: 15 цифр."
                    )
                ],
                verbose_name="ОГРН / ОГРНИП",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="return_address",
            field=models.TextField(blank=True, verbose_name="Адрес возврата товаров"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="seller_type",
            field=models.CharField(
                choices=[("ip", "Индивидуальный предприниматель"), ("company", "Организация")],
                default="ip",
                max_length=20,
                verbose_name="Тип продавца",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="working_hours",
            field=models.CharField(blank=True, max_length=250, verbose_name="Часы связи с покупателями"),
        ),
    ]
