# Generated by Django 5.2.17 on 2026-09-11 17:09

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("checkout_enabled", models.BooleanField(default=False, verbose_name="Оформление включено")),
                ("terms_text", models.TextField(blank=True, verbose_name="Условия продажи / оферта")),
                (
                    "privacy_text",
                    models.TextField(blank=True, verbose_name="Политика обработки персональных данных"),
                ),
                ("delivery_text", models.TextField(blank=True, verbose_name="Условия получения и оплаты")),
            ],
            options={
                "verbose_name": "Настройки магазина",
                "verbose_name_plural": "Настройки магазина",
            },
        ),
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Способ получения")),
                ("slug", models.SlugField(unique=True, verbose_name="Код")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость, ₽",
                    ),
                ),
                ("address_required", models.BooleanField(default=True, verbose_name="Необходим адрес")),
                ("active", models.BooleanField(default=False, verbose_name="Доступен")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Способ получения",
                "verbose_name_plural": "Способы получения",
                "ordering": ["sort_order", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 0)), name="delivery_price_nonnegative"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="Публичный номер"
                    ),
                ),
                ("checkout_key", models.UUIDField(editable=False, unique=True)),
                ("session_key", models.CharField(db_index=True, editable=False, max_length=40)),
                ("name", models.CharField(max_length=160, verbose_name="Получатель")),
                ("phone", models.CharField(max_length=32, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("delivery_method", models.CharField(max_length=160, verbose_name="Способ получения")),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Стоимость товаров"),
                ),
                (
                    "delivery_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Стоимость получения"),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Итого")),
                (
                    "currency",
                    models.CharField(default="RUB", editable=False, max_length=3, verbose_name="Валюта"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("processing", "В обработке"),
                            ("ready", "Передан в доставку / готов к выдаче"),
                            ("completed", "Завершён"),
                            ("canceled", "Отменён"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Исполнение",
                    ),
                ),
                (
                    "financial_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Не оплачен"),
                            ("pending", "Ожидает подтверждения"),
                            ("paid", "Оплачен"),
                            ("part_refunded", "Частично возвращён"),
                            ("refunded", "Возвращён"),
                        ],
                        default="unpaid",
                        editable=False,
                        max_length=20,
                        verbose_name="Оплата",
                    ),
                ),
                ("paid_attempt_id", models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                (
                    "needs_attention",
                    models.BooleanField(default=False, editable=False, verbose_name="Требует внимания"),
                ),
                ("attention_reason", models.TextField(blank=True, editable=False, verbose_name="Причина")),
                ("terms_accepted_at", models.DateTimeField(verbose_name="Условия приняты")),
                (
                    "terms_snapshot",
                    models.TextField(blank=True, editable=False, verbose_name="Принятые условия"),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("total__gt", 0)), name="order_total_positive"),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "total",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("subtotal"), "+", models.F("delivery_price")
                                ),
                            )
                        ),
                        name="order_total_matches_components",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event", models.CharField(max_length=40, verbose_name="Событие")),
                ("recipient", models.EmailField(max_length=254, verbose_name="Получатель")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Отправлено")),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="Попытки")),
                ("last_error", models.CharField(blank=True, max_length=160, verbose_name="Ошибка")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email-уведомление",
                "verbose_name_plural": "Email-уведомления",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "event", "recipient"), name="one_order_notification"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=240, verbose_name="Товар")),
                ("sku", models.CharField(max_length=80, verbose_name="Артикул")),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Цена")),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "vat_code",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Ставка НДС"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="items", to="orders.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="catalog.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
                "ordering": ["pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)), name="order_item_quantity_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unit_price__gt", 0)), name="order_item_price_positive"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="Истекает")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Действует"),
                            ("consumed", "Списан"),
                            ("released", "Освобождён"),
                            ("conflict", "Требует проверки"),
                        ],
                        default="active",
                        max_length=12,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="catalog.product"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "product"), name="one_reservation_per_order_product"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)), name="reservation_quantity_positive"
                    ),
                ],
            },
        ),
    ]
