# Generated by Django 5.2.17 on 2026-09-16 11:32

import django.utils.timezone
from django.db import migrations, models


def prepare_existing_notifications(apps, schema_editor):
    alias = schema_editor.connection.alias
    apps.get_model("orders", "NotificationSettings").objects.using(alias).get_or_create(pk=1)
    notices = apps.get_model("orders", "Notification").objects.using(alias)
    notices.exclude(recipient__iexact=models.F("order__email")).update(audience="manager")


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "manager_email",
                    models.EmailField(
                        blank=True,
                        help_text="Новые и ещё не отправленные уведомления менеджеру. Если пусто — серверный MANAGER_EMAIL.",
                        max_length=254,
                        verbose_name="Email менеджера",
                    ),
                ),
                (
                    "reply_to_email",
                    models.EmailField(
                        blank=True,
                        help_text="Рабочий ящик для вопросов по заказу. Если пусто — адрес менеджера, затем адрес отправителя.",
                        max_length=254,
                        verbose_name="Email для ответов покупателей",
                    ),
                ),
            ],
            options={
                "verbose_name": "Почтовые уведомления",
                "verbose_name_plural": "Почтовые уведомления",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="audience",
            field=models.CharField(
                choices=[("customer", "Покупатель"), ("manager", "Менеджер")],
                default="customer",
                max_length=12,
                verbose_name="Кому",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Создано"),
        ),
        migrations.AddField(
            model_name="notification",
            name="next_attempt_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Следующая попытка"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="payload",
            field=models.JSONField(blank=True, default=dict, verbose_name="Данные события"),
        ),
        migrations.AddField(
            model_name="notification",
            name="skipped_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Пропущено как дубликат"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(max_length=96, verbose_name="Событие"),
        ),
        migrations.RemoveConstraint(model_name="notification", name="one_order_notification"),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=["order", "event", "recipient"],
                condition=models.Q(skipped_at__isnull=True),
                name="one_order_notification",
            ),
        ),
        migrations.RunPython(prepare_existing_notifications, migrations.RunPython.noop),
    ]
