# Generated by Django 5.2.17 on 2026-09-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverymethod",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="По умолчанию в корзине"),
        ),
        migrations.AddField(
            model_name="deliverymethod",
            name="vat_code",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Без НДС"),
                    (2, "НДС 0%"),
                    (3, "НДС 10%"),
                    (4, "НДС 20%"),
                    (5, "НДС 10/110"),
                    (6, "НДС 20/120"),
                    (7, "НДС 5%"),
                    (8, "НДС 7%"),
                    (9, "НДС 5/105"),
                    (10, "НДС 7/107"),
                    (11, "НДС 22%"),
                    (12, "НДС 22/122"),
                ],
                help_text="Выберите с бухгалтером. Для платной доставки без ставки нельзя сформировать чек платёжного сервиса.",
                null=True,
                verbose_name="Ставка НДС доставки для платёжного сервиса",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_vat_code",
            field=models.PositiveSmallIntegerField(
                editable=False, null=True, verbose_name="НДС доставки в заказе"
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="contacts_text",
            field=models.TextField(blank=True, verbose_name="Введение на странице контактов"),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="documents_text",
            field=models.TextField(blank=True, verbose_name="Введение на странице документов"),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="faq_text",
            field=models.TextField(blank=True, verbose_name="Введение на странице вопросов и ответов"),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="returns_text",
            field=models.TextField(blank=True, verbose_name="Возврат и отмена заказа"),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Тексты и настройки обновлены"),
        ),
        migrations.AddConstraint(
            model_name="deliverymethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)), fields=("is_default",), name="one_default_delivery"
            ),
        ),
    ]
