# Generated by Django 5.2.17 on 2026-10-01 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_deliverymethod_is_default_deliverymethod_vat_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverymethod",
            name="cdek_tariff_code",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Подтверждённый тариф от склада до ПВЗ. Стоимость рассчитывается API, поле цены не используется.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Код тарифа СДЭК",
            ),
        ),
        migrations.AddField(
            model_name="deliverymethod",
            name="type",
            field=models.CharField(
                choices=[("static", "Фиксированная стоимость"), ("cdek_pvz", "СДЭК: пункт выдачи")],
                default="static",
                max_length=20,
                verbose_name="Расчёт доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_snapshot",
            field=models.JSONField(default=dict, editable=False, verbose_name="Проверенный расчёт доставки"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                default="static", editable=False, max_length=20, verbose_name="Тип доставки"
            ),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="vat_code",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Без НДС"),
                    (2, "НДС 0%"),
                    (3, "НДС 10%"),
                    (4, "НДС 20%"),
                    (5, "НДС 10/110"),
                    (6, "НДС 20/120"),
                    (7, "НДС 5%"),
                    (8, "НДС 7%"),
                    (9, "НДС 5/105"),
                    (10, "НДС 7/107"),
                    (11, "НДС 22%"),
                    (12, "НДС 22/122"),
                ],
                help_text="Выберите с бухгалтером. Код ставки переводится в формат кассы явно, без изменения значения.",
                null=True,
                verbose_name="Код ставки НДС доставки",
            ),
        ),
    ]
